# "--style",
# "{ BasedOnStyle: llvm,"..
#     "IndentWidth: 4,"..
#     "PenaltyReturnTypeOnItsOwnLine: 1000000,"..
#     "AlignAfterOpenBracket: BlockIndent,"..
#     "ExperimentalAutoDetectBinPacking: false,"..
#     "AlwaysBreakAfterDefinitionReturnType: None,"..
#     "BinPackArguments: false,"..
#     "BinPackParameters: false,"..
#     "AllowAllParametersOfDeclarationOnNextLine: false,"..
#     "ColumnLimit: 88}"

BasedOnStyle: llvm
IndentWidth: 4
PenaltyReturnTypeOnItsOwnLine: 1000000
AlignAfterOpenBracket: BlockIndent
ExperimentalAutoDetectBinPacking: false
AlwaysBreakAfterDefinitionReturnType: None
BinPackArguments: false
BinPackParameters: false
AllowAllParametersOfDeclarationOnNextLine: false
ColumnLimit: 88
